### ISSUE TITLE
Nested Menu in Popover has strange styling

### ISSUE THREAD

**Issue by tgreen7** [palantir/blueprint#2145]
### Bug report

- __Package version(s)__: "@blueprintjs/core": "^1.35.0"
- __Browser and OS versions__: Chrome  64.0.3282.167, MacOS 10.12.6

#### Steps to reproduce

```
 const menu = (
      <Menu>
        <MenuItem text="Submenu">
          <MenuItem text="Child one" />
          <MenuItem text="Child two" />
          <MenuItem text="Child three" />
        </MenuItem>
      </Menu>
    );

    <Popover content={menu}>
        <Button text="Button with Popover Menu" />
    </Popover>
```

<img width="606" alt="screen shot 2018-02-15 at 4 59 02 pm" src="https://user-images.githubusercontent.com/10415101/36288929-0d6c7912-1272-11e8-99d5-960a528ca30b.png">

<img width="53" alt="screen shot 2018-02-15 at 4 59 21 pm" src="https://user-images.githubusercontent.com/10415101/36288928-0d50a304-1272-11e8-91ff-aa7e4504e70a.png">

**Comment by giladgray** [comment]
dang i saw this but i thought I fixed it. (maybe just in 2.0). i think it came from conflicting stylesheets, or bad ordering.

**Comment by giladgray** [comment]
@tgreen7 are you still seeing this? I can't reproduce.

**Comment by tgreen7** [comment]
@giladgray I am still seeing it in one part of my app but am having trouble creating a minimal example.

**Comment by giladgray** [comment]
@tgreen7 pretty sure it's due to conflicting styles. maybe you're applying a class name where you shouldn't be?

i'm going to close this issue as it seems localized to your app. feel free to re-open if you're able to produce a minimal repro.

**Comment by tgreen7** [comment]
@giladgray Sounds good, thanks!
