### ISSUE TITLE
Version dropdown doesn't work

### ISSUE THREAD

**Issue by rootulp** [palantir/blueprint#2791]
#### Environment

- __Package version(s)__:  Current (3.0.0)
- __Browser and OS versions__: https://whatismybrowser.com/w/K5QK42G

#### Steps to reproduce

1. Navigate to https://blueprintjs.com/docs/
1. Click version number next to title
1. Select a version that isn't `v3`

#### Actual behavior

![2018-08-10 14 02 01](https://user-images.githubusercontent.com/3699047/43959310-414e5732-9ca6-11e8-89e9-5c451f581f69.gif)

#### Expected behavior

Clicking `1.39.0` to bring me to docs about that release

**Comment by giladgray** [comment]
fixed in #2776

**Comment by giladgray** [comment]
site deployed

**Comment by flynnham** [comment]
I'd just like to confirm, just cleared my cache and it looks like either the deployed site isn't serving the fix or maybe something else. The issue is still present for me on Chrome 68 (Ubuntu/Elementary Linux) :disappointed:
