### ISSUE TITLE
DateInput popover closes when clicking to month of min/max date when no date is selected

### ISSUE THREAD

**Issue by cnrudd** [palantir/blueprint#3308]
#### Environment

- __Package version(s)__: DateTime 3.6.0
- __Browser and OS versions__: Mac OS 10.14.2  Chrome 71.0.3578.98

#### Steps to reproduce

1. Go to https://blueprintjs.com/docs/#datetime/dateinput
2. Click into the date input field.
3. Delete the date value from the input field, so that the field has no value.
4.  In the popover, navigate forward or backward to the month that contains the max or min date using the <> arrow buttons.  You will see that the popover closes prematurely when it reaches those 'end of range' months.

#### Actual behavior

If no date is selected, the popover closes prematurely when a user clicks on the <> buttons to reach the months that contains the max or min dates.  This prevents a user from selecting a date in those months.  (Well, a user could select a date in those months if he first selects a date that is not in those months, and then clicks into those 'end of range' months, but a user shouldn't have to do that.)

#### Expected behavior

When no date is selected, the popover should stay open when those 'end of range' months are reached by clicking on the <> buttons.  This would allow a date in those months to be selected.

#### Possible solution

If you agree that this is a bug, I'll look into a solution if you haven't found one yet.

**Comment by adidahiya** [comment]
No longer reproducible, I believe this was fixed recently by https://github.com/palantir/blueprint/pull/4316

**Comment by j-perl** [comment]
The problem still occurs for me.

Package version: DateTime 3.20.0
Browser and OS versions: Mac OS 11.1 Chrome 87.0.4280.88

**Comment by cnrudd** [comment]
@ j-perl. Strange.  I cannot reproduce the bug on this page: 
https://blueprintjs.com/docs/#datetime/dateinput

I have the same specs as you:
Package version: DateTime 3.20.0
Browser and OS versions: Mac OS 11.1 Chrome 87.0.4280.88

**Comment by j-perl** [comment]
My bad, I had to reload the web app after running yarn. It's working now. Thanks for looking into it.
