### ISSUE TITLE
Tab navigation not working with Suggest

### ISSUE THREAD

**Issue by thianhtuyet-le** [palantir/blueprint#3945]
#### Environment

- __Package version(s)__: 3.9.0
- __Browser and OS versions__: IE11 (11.950.17134.0) / Edge (42.17134.1.0 & EdgeHTML 17.17134)

#### Steps to reproduce

1. Go to https://blueprintjs.com/docs/#select/suggest
2. Use tab key to focus on Suggest input
3. Press tab again, and the focus will be on the blueprint logo instead of the nearest element (on Chrome, the focus will be on the "Close on select" toggle

#### Actual behavior

Once focused on the Suggest input, when pressing tab, the focus will be on the blueprint logo.

(In my case, something similar happens where the top element will be focused on rather than the next input.)

#### Expected behavior

Upon pressing tab, the focus will be on the nearest element (the "Close on select" toggle in this particular example).

(In my case, the next focus would be on the nearest input).

**Comment by justinbhopper** [comment]
I cannot reproduce this issue.  Perhaps it is fixed now? @thianhtuyet-le

**Comment by stephen** [comment]
This issue is still present in safari (16.4), but not in chrome (114) or firefox (109.1).

repro hitting tab a bunch after focusing the input:
![focus-bug](https://github.com/palantir/blueprint/assets/2320890/5f54d813-b943-4b08-bfa7-b8fe95b9fa0d)
